name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-storybook:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: yarn install
          build_command: yarn build-storybook
          path: storybook-static
          checkout: false
